Add responsive meta tag and update layout to SLIM.
cesium/intra.seium.org pull request #67
Opened 2016-12-16 18:12 UTC by joaofcosta

2016-12-16 20:31 UTC, frm requested changes

2016-12-16 20:31 UTC, frmendes commented on app/views/layouts/application.slim
> +      | SEI'#{@edition.id.to_s.byteslice(2,4)} :: Intranet
This should really just be a helper method.

2016-12-16 20:31 UTC, frmendes commented on app/views/layouts/application.slim
> +<!DOCTYPE html>
You can remove this, can't you?

2016-12-16 20:31 UTC, frmendes commented on app/views/layouts/application.slim
> +
Unnecessary newline

2016-12-16 21:18 UTC, joaofcosta commented on app/views/layouts/application.slim
> +<!DOCTYPE html>
I think, according to [slim website](http://slim-lang.com), that the correct way to do this is `doctype html`.

2016-12-16 21:18 UTC, joaofcosta commented on app/views/layouts/application.slim
> +      | SEI'#{@edition.id.to_s.byteslice(2,4)} :: Intranet
Noted 👍

2016-12-16 21:18 UTC, joaofcosta commented on app/views/layouts/application.slim
> +
Getting picky are we? 😆

2016-12-16 21:23 UTC, joaofcosta commented on app/views/layouts/application.slim
> +<!DOCTYPE html>
@frmendes Forget what I said, did not check what was on line 2...

2016-12-16 21:26 UTC, joaofcosta commented
@frmendes Updated.

2016-12-17 14:47 UTC, frm approved these changes

2016-12-17 19:13 UTC, merged