Add add_organizer and remove_organizer rake tasks.
cesium/intra.seium.org pull request #69
Opened 2016-12-16 18:52 UTC by joaofcosta

2016-12-16 20:29 UTC, frm requested changes

2016-12-16 20:29 UTC, frmendes commented on lib/tasks/add_organizer.rake
> +    if username == nil then
Nobody really uses `then`

2016-12-16 21:22 UTC, joaofcosta commented on lib/tasks/add_organizer.rake
> +    if username == nil then
Removed it 👍

2016-12-17 14:45 UTC, frm approved these changes

2016-12-17 19:12 UTC, closed without merging