Change erb to slim
cesium/intra.seium.org pull request #73
Opened 2016-12-22 18:44 UTC by escolhido

2016-12-22 21:07 UTC, frm requested changes

2016-12-22 21:07 UTC, frmendes commented on app/assets/stylesheets/activities.css.scss
> +	background-color: transparent;
Tabs?

2016-12-26 15:24 UTC, dinocosta requested changes

2016-12-26 15:24 UTC, dinocosta commented on app/views/activities/index.slim
> += stylesheet_link_tag "stylsheets/glyphicons", media: "all"
The path in this stylesheet_link_tag is broken, besides the gplyhicons file is not present in the repository anymore so I think it's safe to remove this line :)

2016-12-26 15:24 UTC, dinocosta commented on app/views/activities/index.slim
> +- (Date.new(@edition.begin_date.year, @edition.begin_date.month, (@edition.begin_date.day - 1))..Date.new(@edition.end_date.year, @edition.end_date.month, @edition.end_date.day)).each do |day|
Maybe you could create a variable in the controller to avoid having this range written here 👍

2016-12-30 20:31 UTC, frm requested changes

2016-12-30 20:31 UTC, frmendes commented on app/controllers/activities_controller.rb
> +    begin_date = Date.new(@edition.begin_date.year, @edition.begin_date.month, (@edition.begin_date.day - 1))
what is this indentation?

2016-12-30 22:14 UTC, joaofcosta commented on app/controllers/activities_controller.rb
> +    begin_date = Date.new(@edition.begin_date.year, @edition.begin_date.month, (@edition.begin_date.day - 1))
😂

2016-12-30 22:15 UTC, frm approved these changes

2016-12-30 22:35 UTC, merged