Fix Devise missing translations error
cesium/intra.seium.org pull request #78
Opened 2017-01-12 14:12 UTC by joaofcosta

- Fix missing pt translations for Devise.
- Add rendering of notices in user profile page so it displays
the successful login message.

2017-01-13 14:09 UTC, joaofcosta commented
@frmendes Should I wait for your approval or just close this? :)

2017-01-13 17:18 UTC, frm requested changes

2017-01-13 17:18 UTC, frmendes commented on config/locales/devise.pt.yml
> +pt:
why pt?

2017-01-14 15:55 UTC, joaofcosta commented on config/locales/devise.pt.yml
> +pt:
@frmendes Because the i18 default locale is set to `:pt` in `config/application.rb`. Should we change it to `:en` and just roll with it?

2017-01-14 16:28 UTC, frmendes commented on config/locales/devise.pt.yml
> +pt:
Change it to `en` and change the default locale. The site's in english either way.

2017-01-15 10:43 UTC, joaofcosta commented on config/locales/devise.pt.yml
> +pt:
@frmendes I agree! Updated it, can you review it? 👍

2017-01-16 10:50 UTC, frm approved these changes

2017-01-16 11:35 UTC, merged