Update Edition Seed and Remove /editions route.
cesium/intra.seium.org pull request #79
Opened 2017-01-16 19:02 UTC by joaofcosta

- Update Edition Seed to the 2017 edition. The application controller was also updated to provide the 2017 edition as `@edition` and navbar urls have also been updated due to this.
- Remove /editions GET path because we are not currently concerned with supporting multiple editions.

2017-01-17 09:36 UTC, frm requested changes
Just that one comment.

2017-01-17 09:36 UTC, frmendes commented on app/controllers/application_controller.rb
> +		@edition    = Edition.find(2017)
Indentation, please.

2017-01-17 21:49 UTC, joaofcosta commented on app/controllers/application_controller.rb
> +		@edition    = Edition.find(2017)
@frmendes I love indenting it like this so it aligns with the equals sign right below 😬
But I get it, will change it :+1:

2017-01-17 21:50 UTC, joaofcosta commented
@frmendes Is it ready for approval now? Haha

2017-01-17 21:52 UTC, frm requested changes

2017-01-17 21:52 UTC, frmendes commented on app/controllers/application_controller.rb
> +		@edition = Edition.find(2017)
Sorry, should've been more specific. It's the leading alignment. It's a tab/4 spaces instead of two.

2017-01-17 21:55 UTC, joaofcosta commented on app/controllers/application_controller.rb
> +		@edition = Edition.find(2017)
Weird how I did not noticed that with VIM 🤔 Will update it :+1:

2017-01-17 21:56 UTC, joaofcosta commented on app/controllers/application_controller.rb
> +		@edition = Edition.find(2017)
@frmendes Done.

2017-01-18 09:44 UTC, frm approved these changes

2017-01-18 12:40 UTC, merged

2017-01-18 14:17 UTC, frmendes commented
@joaofcosta don't forget to delete remote branches.