Update Participants Index View.
cesium/intra.seium.org pull request #82
Opened 2017-01-19 12:07 UTC by joaofcosta

- Update html of participants/index view.
- Add participant-profile-link class.
- Add two helper methods to participants_helper.
- Remove participant-img class from users stylesheet since it already is
present in the participants stylesheet.

2017-01-19 15:15 UTC, frm requested changes

2017-01-19 15:15 UTC, frmendes commented on app/helpers/participants_helper.rb
> +    link_to edition_participant_path(@edition, participant).sub(/\d+\z/, participant.username) do
Why the regex?

2017-01-20 23:35 UTC, joaofcosta commented on app/helpers/participants_helper.rb
> +    link_to edition_participant_path(@edition, participant).sub(/\d+\z/, participant.username) do
@frmendes Did not really thought about that, only limited myself to move it to the helper file. I will review it and I'll get back to you ASAP :+1:

2017-01-20 23:51 UTC, joaofcosta commented on app/helpers/participants_helper.rb
> +    link_to edition_participant_path(@edition, participant).sub(/\d+\z/, participant.username) do
@frmendes Updated it. Also removed `respond_with` from index and show methods in Participants Controller, can they be ignored in this case? I've tried to google it but I don't usually see it being used in this simples cases...

2017-01-23 10:12 UTC, frm approved these changes

2017-01-23 12:00 UTC, merged