Add Amazon AWS image upload to User and Badge.
cesium/intra.seium.org pull request #88
Opened 2017-01-24 22:39 UTC by joaofcosta

2017-01-25 10:34 UTC, frm requested changes
The `dotenv` and new badge should be at a different PR each but oh well. Let it go.

2017-01-25 10:34 UTC, frmendes commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
We have a `:development, :test` group [here](https://github.com/cesium/intra.seium.org/blob/6133e24b4cddf2055217a1d884725045cc6de3c7/Gemfile#L58). You can just put it together. Also, while you're at it, please fix that indentation.

2017-01-25 11:55 UTC, joaofcosta commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
@frmendes Thanks for calling that out, completely missed it... Updated 👍

2017-01-26 22:09 UTC, joaofcosta commented
@frmendes Bump 😆

2017-01-26 23:43 UTC, frm approved these changes

2017-01-27 14:07 UTC, merged