Update & Refactor participants/show view.
cesium/intra.seium.org pull request #92
Opened 2017-02-01 14:43 UTC by joaofcosta

2017-02-01 14:51 UTC, frm requested changes

2017-02-01 14:51 UTC, frmendes commented on app/views/participants/_participant_badges.slim
> +    .col-md-3.col-sm-3.col-xs-6
Extract these into a `app/views/participants/_badge.slim` partial?

2017-02-01 14:51 UTC, frmendes commented on app/views/participants/_participant_info.slim
> +  - if @participant.birthday != nil
Redundant `!= nil`, just `if @participant.birthday`.

2017-02-01 14:51 UTC, frmendes commented on app/views/participants/_participant_info.slim
> +      - if @participant.is_inf_eng_student_at_minho_univ
wat. How about a `@participant.uminho_student(:informatica)`?

2017-02-01 15:35 UTC, joaofcosta commented on app/views/participants/_participant_badges.slim
> +    .col-md-3.col-sm-3.col-xs-6
Sure :+1:

2017-02-01 15:35 UTC, joaofcosta commented on app/views/participants/_participant_info.slim
> +  - if @participant.birthday != nil
Sorry, I copy pasted from another file 😬

2017-02-01 15:36 UTC, joaofcosta commented on app/views/participants/_participant_info.slim
> +      - if @participant.is_inf_eng_student_at_minho_univ
@frmendes Exactly my reaction when I saw it for the first time haha
I agree that it is better to create a method on the Participant model as you recommended. Will get on with it ;)

2017-02-01 15:49 UTC, joaofcosta commented on app/models/user.rb
> +  def uminho_student(course)
@frmendes Is this it? I was trying to wrap my head around if the argument was really needed...

2017-02-02 18:29 UTC, joaofcosta commented
@frmendes Is there anything else I should change or can I close this PR? :)

2017-02-05 12:06 UTC, merged